import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
    title: "Left-Navigation Panel",
    description: "Generated by create next app",
  };

  const navdata=[
    {name:'Skills', href:'/skills'},
    {name:'Education', href:'/education'},
    {name:'Experience', href:'/experience'},

  ]

  export default function NavigationLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <section className="main">
            <ul>
              {
                navdata.map((item)=>{
                return(
                  <li key={item.name}>
                    <Link href={item.href}>
                    {item.name}
                    </Link>
                  </li>

                )
              }
              )
              }
            </ul>
            {children}
        </section>
    );
  }
